WIN_WIDTH = 640     #window width
WIN_HEIGHT = 480    #window height
TILE_SIZE = 32         #size of tiles (in pixels)
FPS = 60
PLAYER_LAYER = 1    #layer of player (above ground)

BLACK = (0, 0, 0)
RED = (255, 0, 0)   #color red (rgb tuple)
GOLD = (206, 184, 136)
GARNET = (120, 47, 64)
SELECTGOLD = (206, 124, 136)

DIALOG_BOX_WIDTH = WIN_WIDTH - WIN_WIDTH//3
DIALOG_BOX_HEIGHT = int((1/4)*WIN_HEIGHT)
DIALOG_BOX_X = int((1/6)*WIN_WIDTH)
DIALOG_BOX_Y = DIALOG_BOX_HEIGHT*3-int((1/6)*DIALOG_BOX_HEIGHT)
DIALOG_BOX_MARGIN = 5

DIALOG_OPTION_WIDTH = int((1/3)*DIALOG_BOX_WIDTH)
DIALOG_OPTION_HEIGHT = int((1/3)*DIALOG_BOX_HEIGHT)
DIALOG_OPTION_X = DIALOG_BOX_X+DIALOG_BOX_WIDTH-DIALOG_OPTION_WIDTH
DIALOG_OPTION_Y = DIALOG_BOX_Y-DIALOG_OPTION_HEIGHT-DIALOG_BOX_MARGIN

DEFAULT_SPEED = 5